### ISSUE TITLE
missing tag

### ISSUE THREAD

**Issue by timsoftgit** [markuskimius/SDL2_Pango#1]
Hi, could you either tag a version of the source code, or mark a version for release. This will allow for archive downloads that need to use checksums. (I need to make a package for Slackware as it is needed for the sdl2 version of tuxpaint, and that requires a non-git method of downloading the source, which can be acheived if the source is tagged with a version or a release version)
many thanks

**Comment by markuskimius** [comment]
Hi Tim,

Tag v0.9.0 has been created.
https://github.com/markuskimius/SDL2_Pango/releases/tag/v0.9.0

Thanks,
Mark

**Comment by timsoftgit** [comment]
many thanks. that was quick :-)
