### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by bkmgit** [markuskimius/SDL2_Pango#2]
From the latest release, the files below have different licenses to those for the main program. Should they be updated?

FSF All Permissive License
SDL2_Pango-2.1.4/INSTALL

FSF Unlimited License (with License Retention)
SDL2_Pango-2.1.4/m4/ltoptions.m4
SDL2_Pango-2.1.4/m4/ltsugar.m4
SDL2_Pango-2.1.4/m4/ltversion.m4
SDL2_Pango-2.1.4/m4/lt~obsolete.m4

FSF Unlimited License (with License Retention) GNU General Public License, Version 2
SDL2_Pango-2.1.4/m4/libtool.m4

GNU General Public License v2.0 or later
SDL2_Pango-2.1.4/ltmain.sh

GNU General Public License v3.0 or later
SDL2_Pango-2.1.4/config.guess
SDL2_Pango-2.1.4/config.sub

GNU Lesser General Public License
SDL2_Pango-2.1.4/docs/html/_s_d_l___pango_8h-source.html

GNU Library General Public License, Version 2.0
SDL2_Pango-2.1.4/test/COPYING

**Comment by markuskimius** [comment]
Thank you for your findings.

I'm not the original author so I'm unable to change any license without the permission of the original author (who we haven't been able to contact for years). But luckily I was able to confirm test/COPYING is not the correct license file, based on the license description the original author made in test/testbench.c. Correspondingly I've updated it to the same license file as COPYING.

As for the remaining files, they were introduced by the build scripts (Autotools/Libtools) which have explicit exception to be distributed under the same license as the rest of the package (which in this case is LGPL 2.1), so they do not require modification.

For example, m4/libtool.m4 explicitly states:

```
# As a special exception to the GNU General Public License, if you
# distribute this file as part of a program or library that is built
# using GNU Libtool, you may include this file under the  same
# distribution terms that you use for the rest of that program.
```

Thanks!
